Dev
prafulrathore/django-stripe-project pull request #2
Opened 2021-05-22 08:03 UTC by prafulrathore

2021-05-22 18:16 UTC, konnerdave requested changes

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
>              return HttpResponse(status=200)
Use Rest Framework Response with Rest Framework status!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
>          return HttpResponse(status=200)
Use Rest Framework Response with Rest Framework status!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +        if event["type"] == "checkout.session.completed":
Just like session complete event, there is another event trigger after you cancel a subscription. Why are you not handling that?

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +            instance = Customer.objects.get(subscription_id=sub_id)
How can you be so sure that the subscription you wanted to delete has been deleted? Don't you think this should be done after you get feedback from the webhook?

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +            instance = Customer.objects.get(subscription_id=sub_id)
Further you should delete subscription from the local subscription model and not the customer!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +            product = Product.objects.create(
Why a new product is being created from a subscription? Subscription creation should rely on a product and not vice versa!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +    Get the Success checkout for the subscription.
Can't understand the meaning of your docstring! Change this to something meaningful and straightforward!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +            context = JsonResponse({"error": str(e)})
Use Rest Framework response or you can also change this to an API's also as the response is JSON!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +        domain_url = "http://localhost:8000/"
Get this from env or settings! The best idea is to get this dynamically from request! Like we get the set fro m`get_current_site`! Think about it!

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
> +    Get the sesssion id based on Stripe primary key.
What is a stripe prmary key?

2021-05-22 18:16 UTC, konnerdave commented on subscription/views.py
>  from django.http import HttpResponse, JsonResponse
Swap them with Rest Framework response. Do some research about which views can be converted to API views!

2021-05-22 18:16 UTC, konnerdave commented on subscription/models.py
> +    subscription_id = models.CharField(max_length=200, default="")
Shift this to a different model named Subscription.

2021-05-22 18:16 UTC, konnerdave commented on subscription/models.py
> +        return f"Price of {self.name} is {self.price} {self.currency}"
Str method shouldn't be this big. Make it small! Furthermore only name should be used in str not the combination of every attribute.

2021-05-22 18:16 UTC, konnerdave commented on subscription/models.py
> +    product_id = models.CharField(max_length=200, default="")
Use the standard limit for CharField throughout the project which is 256.

2021-05-22 18:16 UTC, konnerdave commented on subscription/models.py
>      name = models.CharField(max_length=200)
Make the limit 256 and Shift the name attribute to an abstract model.

2021-05-22 18:16 UTC, konnerdave commented on requirement.txt
> +appdirs==1.4.4
A good idea is to put packages here at the time of installation. That way you will only be mentioning packages which are absolutely necessary and not the dependent ones. pip automatically fetches the dependent one. When you do pip freeze > requirements.txt, it puts all the packages here which becomes a lil confusing to manage.

2021-05-22 18:16 UTC, konnerdave commented on core/views.py
> +        if self.request.user.is_authenticated:
Does this check even matters? I don't see any separate authentication based step below! Remove this!

2021-05-22 18:16 UTC, konnerdave commented on core/views.py
> +    template_name = "core/registration/login.html"
Just for the sake of managing templates in one folder we are rewriting this again. It's not ideal, use the inbuilt ones!

2021-05-22 18:16 UTC, konnerdave commented on core/views.py
> +from django.views.generic.base import TemplateView
Why is this import at the top?

2021-05-22 18:16 UTC, konnerdave commented on core/templates/core/registration/login.html
> +        style="margin-top: 6px; margin-left: 80px"
Never give inline styles, shift this to a CSS file!

2021-05-22 18:16 UTC, konnerdave commented on core/templates/core/registration/login.html
> +{% extends 'core/base.html' %} {% load crispy_forms_tags %} {% block content %}
Write these in 3 separate lines!

2021-05-22 18:16 UTC, konnerdave commented on core/templates/core/registration/login.html
> +<div class="card">
Leave a line or two after the above template tags.

2021-05-22 18:16 UTC, konnerdave commented on core/templates/core/home.html
>    <div class="card" style="width: 22rem;">
Align left!

2021-05-22 18:16 UTC, konnerdave commented on config/urls.py
>      # To the Admin Url
Change this to `Admin URL`

2021-05-22 18:16 UTC, konnerdave commented on config/urls.py
>      # To the Core Url
Change this to `Core URLS`. Although it doesn' matter much as it's pretty much obvious.

2021-05-22 18:16 UTC, konnerdave commented on config/settings.py
>  INSTALLED_APPS = [
You can divide this list into three:-
1. DJANGO_APPS = [ ]
2. PACKAGE_APPS = [ ]
3. CUSTOM_APPS = [ ]
then,
INSTALLED_APPS = DJANGO_APPS +  PACKAGE_APPS + CUSTOM_APPS

2021-05-23 05:40 UTC, prafulrathore commented
Thank you for telling me , i will do!


On Sat, May 22, 2021, 23:47 Himalaya Dave ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432469>
> :
>
> > @@ -109,8 +134,8 @@ def get(self, request):
>              # Invalid signature
>              return HttpResponse(status=400)
>          # Handle the checkout.session.completed event
> -        if event['type'] == 'checkout.session.completed':
> -            session = event['data']['object']
> +        if event["type"] == "checkout.session.completed":
> +            session = event["data"]["object"]
>
>              return HttpResponse(status=200)
>
> Use Rest Framework Response with Rest Framework status!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432494>
> :
>
> > @@ -109,8 +134,8 @@ def get(self, request):
>              # Invalid signature
>              return HttpResponse(status=400)
>          # Handle the checkout.session.completed event
> -        if event['type'] == 'checkout.session.completed':
> -            session = event['data']['object']
> +        if event["type"] == "checkout.session.completed":
> +            session = event["data"]["object"]
>
>              return HttpResponse(status=200)
>          return HttpResponse(status=200)
>
> Use Rest Framework Response with Rest Framework status!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432657>
> :
>
> > @@ -109,8 +134,8 @@ def get(self, request):
>              # Invalid signature
>              return HttpResponse(status=400)
>          # Handle the checkout.session.completed event
> -        if event['type'] == 'checkout.session.completed':
> -            session = event['data']['object']
> +        if event["type"] == "checkout.session.completed":
>
> Just like session complete event, there is another event trigger after you
> cancel a subscription. Why are you not handling that?
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432738>
> :
>
> >              stripe.Subscription.delete(sub_id)
> -            Customer.objects.filter(stripe_subscription_id=sub_id).delete()
> -            Product.objects.filter(subscription_id=sub_id).delete()
> +            # Delete the Customer instance
> +            instance = Customer.objects.get(subscription_id=sub_id)
>
> How can you be so sure that the subscription you wanted to delete has been
> deleted? Don't you think this should be done after you get feedback from
> the webhook?
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432800>
> :
>
> >              stripe.Subscription.delete(sub_id)
> -            Customer.objects.filter(stripe_subscription_id=sub_id).delete()
> -            Product.objects.filter(subscription_id=sub_id).delete()
> +            # Delete the Customer instance
> +            instance = Customer.objects.get(subscription_id=sub_id)
>
> Further you should delete subscription from the local subscription model
> and not the customer!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432889>
> :
>
> >      def get(self, request):
>          # Fetch session id
> -        session = stripe.checkout.Session.retrieve(request.GET['session_id'])
> -        # Get the user and create a new StripeCustomer
> +        session = stripe.checkout.Session.retrieve(request.GET["session_id"])
> +        # Get the Stripe subscription
> +        subscription = stripe.Subscription.retrieve(session.subscription)
> +        # Get the Stripe Product
> +        plan = stripe.Product.retrieve(subscription.plan.product)
> +        try:
> +            # Get the product if its plan exist
> +            product = Product.objects.get(product_id=plan.id)
> +        except Product.DoesNotExist:
> +            # Create a product if doesn't exist
> +            product = Product.objects.create(
>
> Why a new product is being created from a subscription? Subscription
> creation should rely on a product and not vice versa!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637432947>
> :
>
> >          return HttpResponse(context)
>
>
>  class SuccessView(View):
> +    """
> +    Get the Success checkout for the subscription.
>
> Can't understand the meaning of your docstring! Change this to something
> meaningful and straightforward!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637433077>
> :
>
> >
>          except Exception as e:
> -            context = JsonResponse({'error': str(e)})
> +            context = JsonResponse({"error": str(e)})
>
> Use Rest Framework response or you can also change this to an API's also
> as the response is JSON!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637433212>
> :
>
> >      def get(self, request):
> -        domain_url = 'http://localhost:8000/'
> +        domain_url = "http://localhost:8000/"
>
> Get this from env or settings! The best idea is to get this dynamically
> from request! Like we get the set fro mget_current_site! Think about it!
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637433256>
> :
>
> >  from django.views.generic import TemplateView, View
>
>  from subscription.models import Customer, Product
>
>  stripe.api_key = settings.STRIPE_SECRET_KEY
>
>
> -class StripeConfiguration(View):
> -    @method_decorator(login_required)
> +class StripeConfiguration(LoginRequiredMixin, View):
> +    """
> +    Get the sesssion id based on Stripe primary key.
>
> What is a stripe prmary key?
> ------------------------------
>
> In subscription/views.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637433313>
> :
>
> > @@ -1,106 +1,131 @@
>  import stripe
>
>  from django.conf import settings
> -from django.contrib.auth.decorators import login_required
> -from django.contrib.auth.models import User
> -from django.contrib.auth.decorators import login_required
> +from django.contrib.auth.mixins import LoginRequiredMixin
>  from django.http import HttpResponse, JsonResponse
>
> Swap them with Rest Framework response. Do some research about which views
> can be converted to API views!
> ------------------------------
>
> In subscription/models.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637433374>
> :
>
> >      def save(self, *args, **kwargs):
>          self.price = self.price / 100
>          super(Product, self).save(*args, **kwargs)
>
> +
> +class Customer(models.Model):
> +    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
> +    customer_id = models.CharField(max_length=200, default="")
> +    subscription_id = models.CharField(max_length=200, default="")
>
> Shift this to a different model named Subscription.
> ------------------------------
>
> In subscription/models.py
> <https://github.com/prafulrathore/django-stripe-project/pull/2#discussion_r637433388>
> :
>
> >          verbose_name = "Product"
>          verbose_name_plural = "Products"
>
> +    def __str__(self):
> +        return f"Price of {self.name} is {self.price} {self.currency}"
>
> Str method shouldn't be this big. Make it small! Furthermore only name
> should be used in str not the combination of every attribute.
> ----- [...]

2021-05-30 14:16 UTC, merged